import type { Cabinet, Guide, Processor } from './types';

export const processors: Processor[] = [
  { id: 'p1', brand: 'NovaStar', model: 'VX1000', dataPorts: 10, maxPixelsPerPort: 650000 },
  { id: 'p2', brand: 'NovaStar', model: 'VX600', dataPorts: 6, maxPixelsPerPort: 650000 },
  { id: 'p3', brand: 'NovaStar', model: 'VX4S-N', dataPorts: 4, maxPixelsPerPort: 650000 },
  { id: 'p4', brand: 'NovaStar', model: 'MCTRL4K', dataPorts: 16, maxPixelsPerPort: 650000 },
  { id: 'p5', brand: 'NovaStar', model: 'MCTRL300', dataPorts: 2, maxPixelsPerPort: 650000 },
  { id: 'p6', brand: 'NovaStar', model: 'MX40 Pro', dataPorts: 20, maxPixelsPerPort: 650000 },
  { id: 'p7', brand: 'NovaStar', model: 'NovaPro UHD Jr', dataPorts: 16, maxPixelsPerPort: 650000 },
  { id: 'p8', brand: 'NovaStar', model: 'KU20', dataPorts: 6, maxPixelsPerPort: 650000 },
  { id: 'p9', brand: 'NovaStar', model: 'MCTRLR5', dataPorts: 8, maxPixelsPerPort: 650000 },
];

export const cabinets: Cabinet[] = [
  {
    id: 'a_nt29',
    brand: 'Absen',
    model: 'NT2.9 V2',
    pitch: 2.97,
    width: 500,
    height: 500,
    resX: 168,
    resY: 168,
    maxPower: 160,
    avgPower: 53,
    weight: 8.5,
  },
  {
    id: '4b',
    brand: 'Absen',
    model: 'Polaris PL2.9',
    pitch: 2.97,
    width: 500,
    height: 500,
    resX: 168,
    resY: 168,
    maxPower: 130,
    avgPower: 43,
    weight: 7.6,
  },
  {
    id: '4c',
    brand: 'Absen',
    model: 'Polaris PL2.9 XL',
    pitch: 2.97,
    width: 500,
    height: 1000,
    resX: 168,
    resY: 336,
    maxPower: 260,
    avgPower: 86,
    weight: 12.5,
  },
  {
    id: '4',
    brand: 'Absen',
    model: 'Polaris PL3.9',
    pitch: 3.9,
    width: 500,
    height: 500,
    resX: 128,
    resY: 128,
    maxPower: 170,
    avgPower: 56,
    weight: 7.4,
  },
  {
    id: '4d',
    brand: 'Absen',
    model: 'Polaris PL3.9 XL',
    pitch: 3.9,
    width: 500,
    height: 1000,
    resX: 128,
    resY: 256,
    maxPower: 340,
    avgPower: 112,
    weight: 12.5,
  },
  {
    id: 'ab_pl25',
    brand: 'Absen',
    model: 'Polaris PL2.5 Pro',
    pitch: 2.5,
    width: 500,
    height: 500,
    resX: 200,
    resY: 200,
    maxPower: 140,
    avgPower: 46,
    weight: 7.5,
  },
  {
    id: 'd1',
    brand: 'Dinalight',
    model: 'Pro 3.9 Outdoor',
    pitch: 3.91,
    width: 500,
    height: 1000,
    resX: 128,
    resY: 256,
    maxPower: 300,
    avgPower: 100,
    weight: 13,
  },
  {
    id: 'd2',
    brand: 'Dinalight',
    model: 'Pro 2.9 Indoor',
    pitch: 2.97,
    width: 500,
    height: 500,
    resX: 168,
    resY: 168,
    maxPower: 140,
    avgPower: 45,
    weight: 8.0,
  },
  {
    id: 'n1',
    brand: 'Nailpix',
    model: 'Indoor 2.9',
    pitch: 2.97,
    width: 500,
    height: 500,
    resX: 168,
    resY: 168,
    maxPower: 150,
    avgPower: 50,
    weight: 7.5,
  },
  {
    id: 'n2',
    brand: 'Nailpix',
    model: 'Outdoor 3.9',
    pitch: 3.91,
    width: 500,
    height: 500,
    resX: 128,
    resY: 128,
    maxPower: 160,
    avgPower: 55,
    weight: 8.0,
  },
  {
    id: '1',
    brand: 'ROE Visual',
    model: 'Black Pearl BP2V2',
    pitch: 2.84,
    width: 500,
    height: 500,
    resX: 176,
    resY: 176,
    maxPower: 140,
    avgPower: 70,
    weight: 9.4,
  },
  {
    id: 'r_cb3',
    brand: 'ROE Visual',
    model: 'Carbon CB3',
    pitch: 3.75,
    width: 600,
    height: 1200,
    resX: 160,
    resY: 320,
    maxPower: 540,
    avgPower: 270,
    weight: 13.2,
  },
  {
    id: 'r_cb5',
    brand: 'ROE Visual',
    model: 'Carbon CB5',
    pitch: 5.77,
    width: 600,
    height: 1200,
    resX: 104,
    resY: 208,
    maxPower: 540,
    avgPower: 270,
    weight: 13.85,
  },
  {
    id: 'r_rb15',
    brand: 'ROE Visual',
    model: 'Ruby RB1.5F',
    pitch: 1.56,
    width: 500,
    height: 500,
    resX: 320,
    resY: 320,
    maxPower: 160,
    avgPower: 80,
    weight: 9.06,
  },
  {
    id: 'r_rb23',
    brand: 'ROE Visual',
    model: 'Ruby RB2.3F',
    pitch: 2.31,
    width: 500,
    height: 500,
    resX: 216,
    resY: 216,
    maxPower: 150,
    avgPower: 75,
    weight: 7.4,
  },
  {
    id: 'inf_ar39',
    brand: 'INFiLED',
    model: 'AR 3.9',
    pitch: 3.91,
    width: 500,
    height: 1000,
    resX: 128,
    resY: 256,
    maxPower: 300,
    avgPower: 100,
    weight: 12.5,
  },
  {
    id: '2',
    brand: 'Unilumin',
    model: 'Upad III 2.6',
    pitch: 2.6,
    width: 500,
    height: 500,
    resX: 192,
    resY: 192,
    maxPower: 160,
    avgPower: 53,
    weight: 8.5,
  },
  {
    id: '3',
    brand: 'Gloshine',
    model: 'ZS 4.8',
    pitch: 4.81,
    width: 500,
    height: 1000,
    resX: 104,
    resY: 208,
    maxPower: 300,
    avgPower: 100,
    weight: 14,
  },
  {
    id: '5',
    brand: 'Yestech',
    model: 'MG7S 3.9',
    pitch: 3.9,
    width: 500,
    height: 500,
    resX: 128,
    resY: 128,
    maxPower: 150,
    avgPower: 50,
    weight: 5.8,
  }
];

export const guides: Guide[] = [
  {
    id: 'g1',
    issue: 'Módulo o panel completamente negro (Falta de señal)',
    cause: 'Fallo en la comunicación de red, cable RJ45 defectuoso o tarjeta receptora sin energía.',
    solution: '1. Verifica los LEDs indicadores en la tarjeta receptora (Receiving Card). 2. Comprueba el cable CAT5/6 ingresando y saliendo del gabinete. 3. Intercambia el cable por uno nuevo. 4. Asegura que el cable de alimentación interno esté bien conectado a la fuente.',
  },
  {
    id: 'g2',
    issue: 'Líneas brillantes horizontales o verticales',
    cause: 'Daño físico en los LEDs, máscara suelta, o fallo en el IC del módulo (driver).',
    solution: '1. Reemplaza el módulo afectado (Hot swap si el modelo lo permite). 2. Limpia los pines de conexión del módulo a la tarjeta HUB (o tarjeta plana). 3. Verifica si hay pines doblados en la conexión.',
  },
  {
    id: 'g3',
    issue: 'Colores desfasados o extraños (Efecto Mosaico)',
    cause: 'Archivo de calibración o configuración RCFG incorrecto en ese panel específico.',
    solution: '1. Usa el software (ej. NovaLCT) para reenviar la configuración a la tarjeta receptora (Send Receive Card Param). 2. Asegúrate de que el firmware y el lote de calibración coincidan con el resto de la pantalla.',
  },
  {
    id: 'g4',
    issue: 'Parpadeo (Flickering) en una sección de la estructura',
    cause: 'Ruido eléctrico, mala puesta a tierra (grounding), o límite superado en un cable de red (> 650,000 píxeles).',
    solution: '1. Asegura una buena puesta a tierra en la estructura rígida (Truss/Scaffolding). 2. Comprueba que no has superado la capacidad máxima de píxeles para ese puerto del procesador de video. 3. Reduce la frecuencia de refresco temporalmente para diagnosticar.',
  },
  {
    id: 'g5',
    issue: 'Panel no enciende (Ni video, ni LEDs indicadores atrá)',
    cause: 'La fuente de alimentación interna (Power Supply) del gabinete no recibe energía o está quemada.',
    solution: '1. Mide la entrada con un multímetro (Tensión entre Fase y Neutro). 2. Verifica los fusibles del Main Power o distribuidor de corriente. 3. Reemplaza la fuente de alimentación interna.',
  }
];
